version: "3.8"

services:
  db:
    image: mysql
    ports:
     - 3306:3306
    restart: always
    environment:
     - TZ=Asia/Shanghai
     - MYSQL_ROOT_PASSWORD=marry110237.
     - MYSQL_DATABASE=ritui
    volumes:
     - ./mysql/data:/var/lib/mysql
     - ./mysql/my.cnf:/etc/mysql/my.cnf
     - /etc/localtime:/etc/localtime
  nodeserver:
    restart: always
    build:
      context: server
    ports:
      - "3001:3001"
    depends_on:
      - db
  nginx:
    restart: always
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - nodeserver